---
language: node_js
node_js:
  - "node"
branches:
  only:
    - master

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - npm config set spin false
  - npm install -g bower
  - bower --version
  - npm install -g phantomjs-prebuilt
  - phantomjs --version

install:
  - npm install
  - bower install

script:
  - npm test

after_success:
  - cat $DEPLOY_KEY > .travis/deploy_key.pem
  - eval "$(ssh-agent -s)" #start the ssh agent
  - chmod 600 .travis/deploy_key.pem # this key should have push access

  - npm run build:prod
  - cp -a ./dist ../

  - git checkout gh-pages
  - rm -rf *
  - cp ../dist/* .
  - git add .
  - git commit -m "Deploy to GitHub Pages"
  - git push origin gh-pages
